### ISSUE TITLE
Veröffentlichung

### ISSUE THREAD

**Issue by VerHext** [BlockLabTV/LabyMod-Gomme-FriendAutoAccept#1]
Bitte veröffentliche die Datei als "GitHub Release." Und nicht über eine extra "nicht professionelle " webseite.
Würde mir so die Datei nicht runterladen. Viren Gefahr und es sieht so aus als hättest du keinen Plan von GitHub :1st_place_medal: 

https://help.github.com/articles/creating-releases/

Danke :D

**Comment by BlockLabTV** [comment]
Solved
